/** =============================================
  AUTOGENERATED!!!!
  PLEASE DON"T MODIFY THIS FILE!!
  =============================================
  */

import routeConfig1 from './routes';
import routeConfig2 from './apps/Homepage/routes';
import routeConfig3 from './apps/ProductDetail/routes';
import routeConfig4 from './apps/UserDashboard/routes';

const routes = [
  ...routeConfig1,
  ...routeConfig2,
  ...routeConfig3,
  ...routeConfig4,
];

export default routes;
