import fs from 'fs/promises';
import path from 'path';
import { getrouteImportPaths, createGlobalRouteFile } from '../utils';

const rootPath = path.resolve(__dirname, './fixtures');
const srcFolder = 'src';
const routeGlobalRouteFilePath = path.resolve(
  __dirname,
  './fixtures/src/nexus-routes.tsx',
);

describe('nexus-routes-loader', () => {
  it('should return the routes imports', async () => {
    const routeImportPaths = await getrouteImportPaths(rootPath, srcFolder);

    expect(routeImportPaths).toMatchInlineSnapshot(`
      Array [
        "./routes",
        "./apps/Homepage/routes",
        "./apps/ProductDetail/routes",
        "./apps/UserDashboard/routes",
      ]
    `);
  });
  it('should create the global route file that imports all route configurations', async () => {
    const code = await createGlobalRouteFile(rootPath, srcFolder);

    expect(code).toMatchInlineSnapshot(`
      "/** =============================================
        AUTOGENERATED!!!!
        PLEASE DON\\"T MODIFY THIS FILE!!
        =============================================
        */

      import routeConfig1 from './routes';
      import routeConfig2 from './apps/Homepage/routes';
      import routeConfig3 from './apps/ProductDetail/routes';
      import routeConfig4 from './apps/UserDashboard/routes';

      const routes = [
        ...routeConfig1,
        ...routeConfig2,
        ...routeConfig3,
        ...routeConfig4,
      ];

      export default routes;
      "
    `);
    await fs.unlink(routeGlobalRouteFilePath);
  });
});
