/** =============================================
  AUTOGENERATED!!!!
  PLEASE DON"T MODIFY THIS FILE!!
  =============================================
  */

import routeConfig1 from './routes';

const routes = [
  ...routeConfig1,
];

export default routes;
