
name: Release

on:
  push:
    branches:
      - master

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GIO_GITHUB_TOKEN  }}
      - name: Configure git username
        run: |
          git config --global user.name 'Giancarlos Isasi'
          git config --global user.email 'giancarlos.isasi@gmail.com'
      - name: Setup environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
          run_install: true
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > ~/.npmrc
          pnpm release
          pnpm release-publish
          git add .
          git commit -m "chore: release"
          git push --follow-tags
